name: Deploy to GitHub Pages

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Build and Export
      run: pnpm run export
      
    - name: List build output
      run: |
        echo "Build output directory contents:"
        ls -la out/
        echo "Checking for index.html:"
        ls -la out/index.html || echo "index.html not found!"
        echo "Checking for .nojekyll:"
        ls -la out/.nojekyll || echo ".nojekyll not found!"
      
    - name: Create .nojekyll file
      run: touch out/.nojekyll
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/production'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
        force_orphan: true

